import type { Company, Contact, Deal, Activity, Lead, Task } from '@/types'

export const SEED_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Acme Corp',
    industry: 'SaaS',
    website: 'acmecorp.io',
    size: '51-200',
    tags: ['enterprise'],
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'c2',
    name: 'Bright Systems',
    industry: 'Fintech',
    website: 'brightsys.com',
    size: '11-50',
    tags: ['hot-lead'],
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    id: 'c3',
    name: 'Nexus Health',
    industry: 'Healthcare',
    website: 'nexushealth.io',
    size: '201-1000',
    tags: [],
    created_at: '2024-03-01T00:00:00Z',
  },
]

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'p1',
    name: 'Sarah Chen',
    title: 'VP of Engineering',
    email: 'sarah@acmecorp.io',
    phone: '+1 415 555 0101',
    linked_in: 'linkedin.com/in/sarahchen',
    lead_source: 'LinkedIn',
    status: 'Customer',
    tags: ['decision-maker'],
    company_id: 'c1',
    created_at: '2024-01-12T00:00:00Z',
  },
  {
    id: 'p2',
    name: 'Marcus Webb',
    title: 'CTO',
    email: 'mwebb@brightsys.com',
    phone: '+1 628 555 0182',
    linked_in: '',
    lead_source: 'Referral',
    status: 'Prospect',
    tags: [],
    company_id: 'c2',
    created_at: '2024-02-16T00:00:00Z',
  },
  {
    id: 'p3',
    name: 'Priya Nair',
    title: 'Head of Product',
    email: 'priya@nexushealth.io',
    phone: '+1 510 555 0039',
    linked_in: '',
    lead_source: 'Event',
    status: 'Lead',
    tags: ['technical'],
    company_id: 'c3',
    created_at: '2024-03-02T00:00:00Z',
  },
]

export const SEED_LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Elena Torres',
    title: 'Director of Operations',
    email: 'elena@northstarops.com',
    phone: '+1 415 555 0198',
    company_name: 'Northstar Ops',
    website: 'northstarops.com',
    source: 'LinkedIn',
    ingestion_source: 'auto',
    status: 'Augmented',
    notes: 'Matched from LinkedIn search. Needs company validation.',
    tags: ['ops', 'mid-market'],
    company_id: null,
    contact_id: null,
    created_at: '2024-04-05T00:00:00Z',
  },
  {
    id: 'l2',
    name: 'Jordan Miles',
    title: 'Founder',
    email: 'jordan@milecraft.co',
    phone: '',
    company_name: 'Milecraft',
    website: 'milecraft.co',
    source: 'Website',
    ingestion_source: 'manual',
    status: 'Cleaned',
    notes: 'Inbound form. Email verified.',
    tags: ['inbound'],
    company_id: null,
    contact_id: null,
    created_at: '2024-04-12T00:00:00Z',
  },
  {
    id: 'l3',
    name: 'Mina Patel',
    title: 'VP Finance',
    email: 'mina@ledgerbay.io',
    phone: '+1 510 555 0120',
    company_name: 'LedgerBay',
    website: 'ledgerbay.io',
    source: 'Referral',
    ingestion_source: 'manual',
    status: 'Prospecting',
    notes: 'Referral from Bright Systems.',
    tags: ['finance'],
    company_id: null,
    contact_id: null,
    created_at: '2024-04-18T00:00:00Z',
  },
]

export const SEED_DEALS: Deal[] = [
  {
    id: 'd1',
    title: 'Acme Platform License',
    value: 48000,
    stage: 'Negotiation',
    probability: 75,
    close_date: '2024-06-30',
    notes: 'Key stakeholder is Sarah. Pending legal review.',
    company_id: 'c1',
    contact_id: 'p1',
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'd2',
    title: 'Bright Systems Integration',
    value: 22000,
    stage: 'Proposal',
    probability: 50,
    close_date: '2024-07-15',
    notes: 'Sent proposal v2. Waiting on feedback.',
    company_id: 'c2',
    contact_id: 'p2',
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: 'd3',
    title: 'Nexus Health Pilot',
    value: 9500,
    stage: 'Qualified',
    probability: 25,
    close_date: '2024-08-01',
    notes: 'Pilot scope agreed. Budget TBC.',
    company_id: 'c3',
    contact_id: 'p3',
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'd4',
    title: 'Acme Expansion',
    value: 30000,
    stage: 'Lead',
    probability: 10,
    close_date: '2024-09-01',
    notes: 'Intro call done.',
    company_id: 'c1',
    contact_id: 'p1',
    created_at: '2024-04-01T00:00:00Z',
  },
]

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    type: 'call',
    body: 'Intro call with Sarah. Positive reception. Following up with deck.',
    timestamp: '2024-01-22T10:30:00Z',
    deal_id: 'd1',
  },
  {
    id: 'a2',
    type: 'email',
    body: 'Sent proposal deck and pricing sheet.',
    timestamp: '2024-02-01T14:00:00Z',
    deal_id: 'd1',
  },
  {
    id: 'a3',
    type: 'meeting',
    body: 'Demo with Marcus and his team. Strong interest in API integrations.',
    timestamp: '2024-02-21T11:00:00Z',
    deal_id: 'd2',
  },
  {
    id: 'a4',
    type: 'note',
    body: 'Priya mentioned budget approval needed from CFO.',
    timestamp: '2024-03-12T09:00:00Z',
    deal_id: 'd3',
  },
]

export const SEED_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Follow up on legal review',
    due_date: '2024-06-20',
    priority: 'high',
    status: 'open',
    deal_id: 'd1',
    contact_id: null,
  },
  {
    id: 't2',
    title: 'Send revised proposal to Marcus',
    due_date: '2024-07-01',
    priority: 'medium',
    status: 'open',
    deal_id: 'd2',
    contact_id: null,
  },
  {
    id: 't3',
    title: 'Schedule CFO intro call',
    due_date: '2024-07-10',
    priority: 'low',
    status: 'open',
    deal_id: 'd3',
    contact_id: null,
  },
  {
    id: 't4',
    title: 'Prep onboarding doc for Acme',
    due_date: '2024-06-15',
    priority: 'high',
    status: 'done',
    deal_id: 'd1',
    contact_id: null,
  },
]
